# Generated by Django 4.0 on 2021-12-23 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boardlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('done', models.BooleanField(default=False)),
                ('boardlist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='boardlist.boardlist')),
            ],
        ),
    ]
