# Generated by Django 4.0 on 2021-12-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('card', '0001_initial'),
        ('card_items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='labels', to='card_items.Label'),
        ),
    ]
