# Generated by Django 4.0 on 2021-12-23 18:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('card', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='members',
            field=models.ManyToManyField(related_name='cards_as_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
