# Generated by Django 4.0 on 2021-12-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardlist',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
