# Generated by Django 4.0 on 2021-12-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/boards')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('blocked', 'Blocked')], default='private', max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'Board',
                'verbose_name_plural': 'Boards',
            },
        ),
    ]
